#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_gap 25
yabai -m config top_padding 28
yabai -m config bottom_padding 25
yabai -m config left_padding 25
yabai -m config right_padding 25

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

yabai -m config auto_balance on
yabai -m config split_ratio 0.5

yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Activity Monitor" manage=off

# SketchyBar integration
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
