#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_gap 12
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0

# Mouse support for window operations
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config normal_window_opacity 1.0

yabai -m config auto_balance on
yabai -m config split_ratio 0.5

yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Activity Monitor" manage=off

